---
zones:
  internal.lan:
    reverse: 1.168.192.in-addr.arpa
  iot.internal.lan:
    reverse: 2.168.192.in-addr.arpa
hosts:
  server:
    zone: internal.lan
    ip: 192.168.1.2
    ipv6: fe80::ec4:7aff:fe95:e4ca
    no_dhcp: true
    web:
      services:
        PLEX:
          url: ":32400/web"
          mode: http
        Grafana:
          url: ":3000"
          mode: http

  brother:
    zone: internal.lan
    ip: 192.168.1.3
    mac: 3c:2a:f4:c9:5a:a9
    web:
      services:
        Frontend:
          url: "/"
          mode: http

  hue:
    zone: iot.internal.lan
    ip: 192.168.1.4
    mac: 7c:2f:80:cb:b3:3b

  