---
zones:
  internal.lan:
    reverse: 1.168.192.in-addr.arpa
    subnet: 192.168.1.0/24
    description: Main network
    expanded: "true"
    hosts:
      server:
        ip: 192.168.1.2
        ipv6: fe80::ec4:7aff:fe95:e4ca
        no_dhcp: true
        web:
          services:
            PLEX:
              url: ":32400/web"
              mode: http
            Grafana:
              url: ":3000"
              mode: http
      brother:
        ip: 192.168.1.3
        mac: 3c:2a:f4:c9:5a:a9
        web:
          services:
            Frontend:
              url: "/"
              mode: https
  iot.internal.lan:
    reverse: 2.168.192.in-addr.arpa
    expanded: "false"
    subnet: 192.168.2.0/24
    description: IoT Devices
    hosts:
      hue:
        ip: 192.168.2.2
        mac: 7c:2f:90:af:b3:4e